#! /usr/bin/zsh
# -----------------------------------------
# Init Process
# -----------------------------------------
    
    # Prvent loading twice
    if [ -z "$_DOTZSHRC_LOADED" ]; then
        _DOTZSHRC_LOADED=1
    else
        return
    fi
    # Exit for non-interactive shell
    [[ $- != *i* ]] && return

    # Ubuntu temp fix for snap format package
    if [ -f "/etc/profile.d/apps-bin-path.sh" ] ; then
        source /etc/profile.d/apps-bin-path.sh
    fi

    # Auto Install zinit
    ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
    [ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
    [ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
    source "${ZINIT_HOME}/zinit.zsh"

# -----------------------------------------
# Option Setting Zone
# -----------------------------------------
    # emulate -lLR zsh  -> list all opt
    # setopt -> list opt differnt to default
    setopt AUTO_CD #No exec -> cd to it
    bindkey -e

# -----------------------------------------
# History Setting Zone
# -----------------------------------------
    
    

# -----------------------------------------
# Complete Setting Zone
# -----------------------------------------
# Complete and Prompt 
autoload -Uz compinit 


# 设置 walters 主题的默认命令行提示符
export PS1="[%n@%m:%~]%# "


zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
  atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull'zinit creinstall -q .' \
      zsh-users/zsh-completions


zinit ice as"command" from"gh-r" \
          atclone"./starship init zsh > init.zsh; ./starship completions zsh > _starship" \
          atpull"%atclone" src"init.zsh"
zinit light starship/starship


bindkey '^F' autosuggest-accept




# source ~/.config/pem/shell/fzf/fzf-ff.sh
# source ~/.config/pem/shell/vless/vless.sh
source ~/.config/pem/shell/init-sh.sh
source ~/.config/chezmoi/chezmoi.zsh

