onboarding = false
[theme]
name = "one-dark"
auto_switch = false

[ui]
pane_gaps = false
prompt_new_tab_name = false

[keys]
prefix = "ctrl+b"
detach = "prefix+d"

focus_pane_left = "ctrl+alt+h"
focus_pane_down = "ctrl+alt+j"
focus_pane_up = "ctrl+alt+k"
focus_pane_right = "ctrl+alt+l"

new_tab = "ctrl+alt+w"
next_tab = "ctrl+alt+e"
previous_tab = "ctrl+alt+q"

split_vertical = "ctrl+alt+c"
close_pane = "ctrl+alt+x"
zoom = "ctrl+alt+z"
