onboarding = false

[theme]
name = "one-dark"
auto_switch = false

[theme.custom]
# Change the dim gray to OneDark's normal text color. Numbers on unnamed tabs will become noticeably brighter.
overlay0 = "#abb2bf"
# # Optional: Make the inactive tab background slightly darker for stronger contrast with the numbers.
surface0 = "#21252b"

[ui]
pane_gaps = false
prompt_new_tab_name = false
pane_outer_borders = false

[keys]
prefix = "ctrl+b"
detach = ["prefix+q", "prefix+d"]

focus_pane_left = "ctrl+alt+h"
focus_pane_down = "ctrl+alt+j"
focus_pane_up = "ctrl+alt+k"
focus_pane_right = "ctrl+alt+l"

new_tab = ["ctrl+alt+w", "prefix+n"]
next_tab = "ctrl+alt+e"
previous_tab = "ctrl+alt+q"
rename_tab = ["prefix+,", "prefix+shift+t"]

split_vertical = ["ctrl+alt+c", "prefix+c"]
close_pane = ["ctrl+alt+x", "prefix+x"]
zoom = ["ctrl+alt+z", "prefix+z"]


[[keys.command]]
key = "alt+shift+h"
type = "shell"
command = "herdr-passthough if-proc '^(g?(view|l?n?vim?x?))(diff)?$' alt+shift+h herdr pane focus --direction left --current"

[[keys.command]]
key = "alt+shift+j"
type = "shell"
command = "herdr-passthough if-proc '^(g?(view|l?n?vim?x?))(diff)?$' alt+shift+j herdr pane focus --direction down --current"

[[keys.command]]
key = "alt+shift+k"
type = "shell"
command = "herdr-passthough if-proc '^(g?(view|l?n?vim?x?))(diff)?$' alt+shift+k herdr pane focus --direction up --current"

[[keys.command]]
key = "alt+shift+l"
type = "shell"
command = "herdr-passthough if-proc '^(g?(view|l?n?vim?x?))(diff)?$' alt+shift+l herdr pane focus --direction right --current"

[[keys.command]]
key = "alt+shift+c"
type = "shell"
command = "herdr-passthough if-proc '^(g?(view|l?n?vim?x?))(diff)?$' alt+shift+c herdr pane split --direction right"

[[keys.command]]
key = "alt+shift+x"
type = "shell"
command = "herdr-passthough if-proc '^(g?(view|l?n?vim?x?))(diff)?$' alt+shift+x herdr pane close $HERDR_ACTIVE_PANE_ID"
