aliases:
  # command: ["alias1", "alias2"]

max-array-values: 500
max-string-len: 500
max-variable-recurse: 3
disassemble-flavor: go
show-location-expr: true

# List of directories to use when searching for separate debug info files.
debug-info-directories: ["/usr/lib/debug/.build-id"]
